apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"fastapi-service","namespace":"default"},"spec":{"ports":[{"port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"fastapi"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-02-26T10:07:53Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: fastapi-service
  namespace: default
  resourceVersion: "2802"
  uid: 49a2fb35-4384-46ea-a719-287de7676a75
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.234.11
  clusterIPs:
  - 10.0.234.11
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30129
    port: 8000  # 🔥 Changed from 80 to 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fastapi
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.214.70.151
      ipMode: VIP
